const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: M3.surface },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: M3.surface },
  content: { paddingHorizontal: 24, paddingBottom: 120 },

  header: { paddingTop: 60, marginBottom: 24, flexDirection: 'row', alignItems: 'center', gap: 12 },
  headerLabel: { fontFamily: 'Inter_500Medium', fontSize: 11, color: M3.onSurfaceVariant, letterSpacing: 2 },
  headerTitle: { fontFamily: 'Manrope_800ExtraBold', fontSize: 28, color: M3.primary, letterSpacing: -0.5 },
  backBtn: { padding: 4 },
  categoryBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  categoryText: { fontFamily: 'Inter_600SemiBold', fontSize: 10, letterSpacing: 1 },

  sectionLabel: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 11,
    color: M3.onSurfaceVariant,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 12,
    marginTop: 8,
  },
  pickerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: M3.surfaceContainerLowest,
    borderRadius: 12,
    marginBottom: 8,
  },
  pickerItemActive: { backgroundColor: `${M3.secondaryFixed}50` },
  pickerText: { fontFamily: 'Inter_500Medium', fontSize: 14, color: M3.onSurface },
  pickerTextActive: { color: M3.secondary, fontFamily: 'Inter_600SemiBold' },
  pickerSub: { fontFamily: 'Inter_400Regular', fontSize: 11, color: M3.onSurfaceVariant, marginTop: 2 },

  emptyState: { alignItems: 'center', paddingTop: 60, gap: 8 },
  emptyText: { fontFamily: 'Manrope_700Bold', fontSize: 16, color: M3.onSurfaceVariant },
  emptySub: { fontFamily: 'Inter_400Regular', fontSize: 13, color: M3.outline },

  problemCard: {
    backgroundColor: M3.surfaceContainerLow,
    borderRadius: 12,
    padding: 24,
    marginBottom: 24,
  },
  problemStatement: {
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 18,
    color: M3.onSurface,
    lineHeight: 26,
  },

  answerLabel: { fontFamily: 'Manrope_700Bold', fontSize: 18, color: M3.onSurface, marginBottom: 12 },
  answerInput: {
    minHeight: 200,
    backgroundColor: M3.surfaceContainerHighest,
    borderRadius: 12,
    padding: 20,
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    color: M3.onSurface,
    lineHeight: 22,
    marginBottom: 20,
  },

  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: M3.primary,
    paddingVertical: 16,
    borderRadius: 12,
  },
  primaryBtnText: { fontFamily: 'Manrope_700Bold', fontSize: 15, color: M3.onPrimary },

  gradeRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 20 },
  gradeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
  },
  gradeText: { fontFamily: 'Manrope_700Bold', fontSize: 15 },

  feedbackCard: {
    backgroundColor: M3.surfaceContainerLowest,
    padding: 20,
    borderRadius: 16,
    marginBottom: 20,
  },
  feedbackText: { fontFamily: 'Inter_400Regular', fontSize: 14, color: M3.onSurface, lineHeight: 22 },

  modelAnswer: {
    backgroundColor: M3.inverseSurface,
    padding: 20,
    borderRadius: 12,
    borderTopRightRadius: 24,
    marginBottom: 16,
  },
  modelAnswerHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  modelAnswerTitle: { fontFamily: 'Manrope_700Bold', fontSize: 16, color: M3.inverseOnSurface },
  modelAnswerText: { fontFamily: 'Inter_400Regular', fontSize: 13, color: M3.outlineVariant, lineHeight: 20 },

  nextBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: M3.surfaceContainerHighest,
    paddingVertical: 16,
    borderRadius: 12,
    marginTop: 8,
  },
  nextBtnText: { fontFamily: 'Manrope_700Bold', fontSize: 15, color: M3.primary },
});
